name: CI-Hurl-Test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: echo "Building app..."
      - name: Integration test
        run: |
          wget https://github.com/Orange-OpenSource/hurl/releases/download/4.3.0/hurl-4.3.0-x86_64-unknown-linux-gnu.tar.gz
          tar xzvf hurl-4.3.0-x86_64-unknown-linux-gnu.tar.gz
          hurl-4.3.0-x86_64-unknown-linux-gnu/bin/hurl --test sample.hurl sample-1.hurl
